name: Run Unit Test - Angular
# run-name: ${{ github.actor }} is testing out GitHub Actions 
on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
    workflow_call:
      inputs:
         myInput:
            required: true
            type: 'string'
            default: 'test'
jobs:
    Run-unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Run UT
              if: ${{ inputs.myInput }}
              run: |
                  echo "${{ inputs.myInput }}"

