name: Run Unit Test - Angular
# run-name: ${{ github.actor }} is testing out GitHub Actions 
on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
    Run-unit-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
            - run: java --version
            - run: npm ci
            - run: npm test
