name: Run Unit Test - Angular
# run-name: ${{ github.actor }} is testing out GitHub Actions 
on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
    workflow_call:
      inputs:
         ut-gradle-command:
            required: false
            type: 'string'
            default: "test jacocoTestCoverageVerification"
jobs:
    Run-unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Run UT
              run: |
                  export xyz =  (${{ github.inputs.ut-gradle-command }})
                  echo $xyz

